[package]
name = "airmail"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = "0.15.0"
clap = { version = "4.4.18", features = ["derive"] }
futures-util = "0.3.30"
geojson = "0.24.1"
levenshtein_automata = "0.2.1"
s2 = "0.0.12"
tantivy = "0.21.1"
tantivy-common = "0.6.0"
tantivy-fst = "0.4.0"
tempfile = "3.9.0"
airmail_common = { path = "../airmail_common" }
deunicode = "1.4.2"
regex = "1.10.3"
lazy_static = "1.4.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.196", features = ["derive"] }
log = "0.4.20"
env_logger = "0.11.1"
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
rayon = "1.8.1"
serde_json = "1.0.113"
airmail_parser = { path = "../airmail_parser" }

[[bin]]
name = "index"

[[bin]]
name = "query"
